[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = '''
      default-src 'self';
      img-src 'self' data: https:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com;
    '''

# Configuração de MIME types
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

# Redireciona todas as rotas para o index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redireciona rotas específicas
[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/index.html"
  status = 200

# Página 404 personalizada
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 